import Head from "next/head";
import Layout from "@/components/layout";
import { getServerSidePropsWithAuth } from "@/lib/server";

export default function Home() {
  return (
    <>
      <Head>
        <title>Director&apos;s Access</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout activeRoute="home">{null}</Layout>
    </>
  );
}

export const getServerSideProps = getServerSidePropsWithAuth();
